version: '3'
services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3016:3016'
      - '3017:3017'
    volumes:
      - .:/app
    depends_on:
      - database
    environment:
      - APP_PORT=3017
      - EXPRESS_SERVER_PORT=3016
      - SLACK_SIGNING_SECRET=
      - OPENAI_API_KEY=
      - SLACK_BOT_TOKEN=
  database:
    image: sqlite:latest
    volumes:
      - ./users.db:/app/users.db
