version: '1'
services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3016:3016'
      - '3017:3017'
    volumes:
      - ./users.db:/app/users.db
    environment:
      - APP_PORT=3017
      - EXPRESS_SERVER_PORT=3016
      - SLACK_SIGNING_SECRET=c554294484a9ba86c93cf373c301777e
      - OPENAI_API_KEY=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
      - SLACK_BOT_TOKEN=xoxb-5547928716115-5551914937252-Ja9BdgG9ZtljMVbOpdZk3BpF
  
